openapi: 3.0.3
info:
  title: Product API
  version: 1.0.0
paths:
  /v1/products:
    get:
      summary: Get all products
      operationId: getProducts
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/product'
components:
  schemas:
    product:
      type: object
      properties:
        id:
          type: string
          example: "p001"
        name:
          type: string
          example: "Widget"
