openapi: 3.0.3
info:
  title: Order API
  version: 1.0.0
paths:
  /v1/orders:
    get:
      summary: Get all orders
      operationId: getOrders
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/order'
components:
  schemas:
    order:
      type: object
      properties:
        id:
          type: string
          example: "o123"
        total:
          type: number
          example: 99.99
