openapi: 3.0.3
info:
  title: User API
  version: 1.0.0
paths:
  /v1/users:  # Versionné
    get:
      summary: Get all users
      description: Retrieves a paginated list of users with authentication.
      operationId: getAllUsers  # camelCase
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'
        '401':
          description: Unauthorized
        '500':
          description: Server Error
components:
  schemas:
    user:  # camelCase
      type: object
      properties:
        id:
          type: string
          example: "123"
        username:
          type: string
          example: "johndoe"
